import type { Metadata } from 'next'
import '../../globals.css'
import AdminNavbar from '../../../components/shared/admin-navbar'

export const metadata: Metadata = {
    title: 'LiteraCrypto',
    description: 'Generated by LiteraCrypto',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body >
                <AdminNavbar/>
                {children}
            </body>
        </html>
    )
}