import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../../globals.css'
import AdminNavbar from '../../../components/shared/admin-navbar'



const inter = Poppins({
    subsets: ["latin"],
    weight: '400'
})

export const metadata: Metadata = {
    title: 'LiteraCrypto',
    description: 'Generated by LiteraCrypto',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <AdminNavbar/>
                {children}
            </body>
        </html>
    )
}