import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { auth } from '../auth'
import './globals.css'
import Footer from '../components/shared/footer'
import About from '../components/shared/about'
import Navbar from '../components/shared/navbar'
import { AnimatePresence } from 'framer-motion'

export const metadata: Metadata = {
  title: 'LiteraCrypto',
  description: 'Generated by LiteraCrypto',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body>
          <Navbar/>
          {children}
          <About/>
          <Footer/>
        </body>
      </html>
    </SessionProvider>
  )
}